spring:
  data:
    mongodb:
      username: matimbe
      password: matimbe
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.matimbe.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.matimbe.ecommerce.notification.PaymentNotificationRequest


  application:
    name: notification-service
